### ISSUE TITLE
tendermint/0.33 / #196 followup issue

### ISSUE THREAD

**Issue by Liamsi** [informalsystems/tendermint-rs#211]
Collecting all outstanding discussions for full 0.33 compatibility and review comments from #196 and #199 and related issues here:

- [x] Add changelog entries before release
- [x] address @melekes comments: https://github.com/informalsystems/tendermint-rs/pull/196#pullrequestreview-394541450 (addressed in #296)
---
 - [x] JSON / RPC issues: https://github.com/informalsystems/tendermint-rs/pull/196#issuecomment-611969478 and https://github.com/informalsystems/tendermint-rs/pull/196#issuecomment-611982250
- [x] investigate why above isn't detected by the integration tests

@ancazamfir re-tested this and it 
> Seems ok now

This was likely resolved as part of the serialization refactoring @greg-szabo did.

---
- [x] tests for jsonrpc ID: https://github.com/informalsystems/tendermint-rs/pull/196#discussion_r399790732 (done in #298 )
- [x] err handling weirdness: https://github.com/informalsystems/tendermint-rs/pull/196#discussion_r399782582 (this got resolved / outdated in the several serialzation improvement PRs and using blockIfFlags)
- [x] review of #199: https://github.com/informalsystems/tendermint-rs/pull/199#discussion_r401985251, https://github.com/informalsystems/tendermint-rs/pull/199#discussion_r401987638, https://github.com/informalsystems/tendermint-rs/pull/199#discussion_r406830449 (time was addressed in #277 and the remaining work was done in the commitsig refactoring PRs)
 - [x] delete AsRef completely: https://github.com/informalsystems/tendermint-rs/pull/196#discussion_r400539671 (was done after 0.33 PR was merged)
- [x] move Proof: https://github.com/informalsystems/tendermint-rs/pull/206#pullrequestreview-390017106 (done in: https://github.com/informalsystems/tendermint-rs/pull/297)

**Comment by Liamsi** [comment]
I think https://github.com/informalsystems/tendermint-rs/pull/196#issuecomment-611969478 is resolved. At least I would think this would be caught by the integration tests 🙏

**Comment by Liamsi** [comment]
>  tests for jsonrpc ID: #196 (comment)

This would become obsolete if we switched to using an jsonrpc library instead. Otherwise the tests I had in mind would look similar to: https://github.com/paritytech/jsonrpc/blob/ef92a481d76802da489f0f57dfdf4d459d7f7f76/core/src/types/id.rs#L16

**Comment by Liamsi** [comment]
Regarding the last point:
>  move Proof: #206 (review)
 There is also a separate tracking issue:  https://github.com/informalsystems/tendermint-rs/issues/207
Will comment there but tldr: the struct in abci is only there for serialzation. So it is in fact the right place.

**Comment by Liamsi** [comment]
This issue can be closed when #297 and #298 are merged.

**Comment by Liamsi** [comment]
All comments addressed as far as I can see.
