### ISSUE TITLE
Light Client: Follow-up

### ISSUE THREAD

**Issue by romac** [informalsystems/tendermint-rs#280]
- [x] Introduce `clockDrift` parameter, as per the spec
- [x] Write documentation
- [x] Tag code as per the traceability proposal
- [x] Add new tags to the English spec
- [x] Add tag versions to the English spec
- [x] See whether we need to re-introduce the `TrustedStoreReader/Writer` wrappers (we don't)
- [ ] Add support for verifying headers lower than the latest trusted state - #361 
- [ ] Add [structured logging](https://docs.rs/tracing)
- [ ] Streamline creation of a light client instance and supervisor
    - [ ] Use the [builder pattern](https://www.ameyalokare.com/rust/2017/11/02/rust-builder-pattern.html) to create and initialize the `LightClient` and `Supervisor`
- [ ] Write units tests for new components - #320
- [ ] Port current light client unit tests - #320 
- [ ] Remove previous lite client code in `tendermint` crate - #342 
- [x] Address comments in #294

---

Other issues we may want to fix as well as part of this follow-up:

- [x] #276
- [x] #137
- [ ] #235
- [x] #138 
- [x] #136 (mostly done in #237)

---

These tasks should be handled in separate issue and PRs:

- Implement CLI for running a standalone light client + RPC server

**Comment by ebuchman** [comment]
I believe all the points have either been addressed or given new issues except for:

- [ ] Add [structured logging](https://docs.rs/tracing)
- [ ] Streamline creation of a light client instance
    - [ ] Use the [builder pattern](https://www.ameyalokare.com/rust/2017/11/02/rust-builder-pattern.html) to create and initialize the `LightClient`

@romac want to open separate issues for these and then we can close this one?

**Comment by romac** [comment]
Done in #421 and #422.
