### ISSUE TITLE
High Level Goals for the next Third

### ISSUE THREAD

**Issue by ebuchman** [informalsystems/tendermint-rs#388]
This is a high level overview of potential plans for this repo over the next few months:

## Priorities
- [x] Wrap up the light-client release - https://github.com/informalsystems/tendermint-rs/milestone/1 (any other issues?)~~
- [x]  Wrap up the light-client verification spec (support with IBC)
- [x] Integrate model-based testing for the light client and more comprehensive test suite - #320, #330, #393 
- [ ] Support IBC effort with anything it might need from light-client or tendermint types - https://github.com/informalsystems/ibc-rs/issues/60
- [ ] Fork accountability spec and support for the Go implementation 
- [ ]  Light Client Evidence Submission - #415
- [x] Upgrade to be compatible with Tendermint v0.34 (ie. protobuf migration!) - #305 

## Common Goals
- [x] Wrap up the fork detection English spec (not sure if we should focus on the TLA+ for it now)
- [x] Absorb rust-abci repo (and potentially build out a rust abci client) - #29 
  - [ ]  Potentially also support some very basic application development framework
- [x] Improve the websocket connection - #311, #313 
- [x]  Release 0.16.0 - https://github.com/informalsystems/tendermint-rs/milestone/3
- [ ] Type Generalizations - #416
- [x]  Productionization Efforts  (documentation, crate organization, release process) - #323 
- [x] Compiling to WASM - #463

## Stretch Goals
- [ ] Implement the Tendermint MConnection, bring back SecretConnection from tmkms, and run a simple node that can make p2p connections to tendermint full nodes and exchange PEX messages (without any logic or address book ...) - to discuss and open issues about

**Comment by tomtau** [comment]
I may suggest absorbing @devashishdxt https://github.com/devashishdxt/abci-rs instead, as 1) it works with rust async (so doesn't bring in legacy tokio 0.1 deps), 2) it was planned to replace the current rust-abci implementation:
https://github.com/tendermint/rust-abci/pull/112 but delayed for the moment.

So I think it's a better starting point -- instead of the custom wrapper types, it can perhaps reuse parts of tendermint-rs?

**Comment by marbar3778** [comment]
> I may suggest absorbing @devashishdxt's rearchitected [devashishdxt/abci-rs](https://github.com/devashishdxt/abci-rs) instead, as 1) it works with rust async, 2) has some desired features in place (e.g. unix domain socket support), 3) it was planned to replace the current rust-abci implementation:
> [tendermint/rust-abci#112](https://github.com/tendermint/rust-abci/pull/112) but delayed for the moment.

I agree with making this change. I would just like to point out that this may change some of the goals listed above as the current implementation may not be compatible with 0.34 of Tendermint-Go (state-sync, block pruning, runtime event indexing, ...).

**Comment by tomtau** [comment]
> > I may suggest absorbing @devashishdxt's rearchitected [devashishdxt/abci-rs](https://github.com/devashishdxt/abci-rs) instead, as 1) it works with rust async, 2) has some desired features in place (e.g. unix domain socket support), 3) it was planned to replace the current rust-abci implementation:
> > [tendermint/rust-abci#112](https://github.com/tendermint/rust-abci/pull/112) but delayed for the moment.
> 
> I agree with making this change. I would just like to point out that this may change some of the goals listed above as the current implementation may not be compatible with 0.34 of Tendermint-Go (state-sync, block pruning, runtime event indexing, ...).

will any of those have a big impact on abci-rs? For state-sync, it may just be protobuf update + extra trait / functions for it + expecting one more TCP/UDS connection?

**Comment by thanethomson** [comment]
I think this issue's been open for much longer than the initially anticipated quarter :slightly_smiling_face: I'm closing it for now in favor of the [Q3 2021 milestone](https://github.com/informalsystems/tendermint-rs/milestone/14). I've moved the majority of the still-open issues/requirements to this new milestone with the exception of:

- Fork accountability spec and support for the Go implementation (is there an issue specifically for this somewhere in one of our repos?)
- Type generalizations #416
