### ISSUE TITLE
Cleaner directory structure

### ISSUE THREAD

**Issue by ebuchman** [informalsystems/tendermint-rs#697]
This is a follow/update to #7. Splitting it into two sections: high level repo structure, and re-organization of `tendermint` crate

Repo structure:

- [ ] secret connection will be moved back in here, likely as part of a new p2p crate - #691. 
- [ ] rust abci will be moved in here - #29 
- [ ] light-node should commit to the Cargo.lock - https://github.com/informalsystems/tendermint-rs/issues/7#issuecomment-645514338

The `tendermint` crate is still a jumble of top level modules with minimal organizational structure. Some tasks and questions we should figure out:

- [ ] Should we put the [integration tests ]( https://github.com/informalsystems/tendermint-rs/tree/master/tendermint/tests) in a separate crate? Then, we could get rid of the dev-dependency to rpc inside of tendermint-rs (https://github.com/informalsystems/tendermint-rs/issues/7#issuecomment-646884727)
- [ ] Should `crypto` and `config` be factored out of the `tendermint` crate into their own crates? `config` doesn't have any unique dependencies and `crypto` will always be needed by the tendermint crate. I guess the question is if there's a use case for importing crypto without importing the rest of the tendermint crate?
- [ ] `lite` module should be removed now that `light-client` crate is in place. Is there anything left to take from it? Can it just be deleted outright? Alternatively, if the `light-client` is type generalized (per #416 ), then `tendermint` crate may still need a `light` module with its implementation of the `light-client` types?
- [ ] should p2p specific types (channel, moniker, net, node) be moved to the new `p2p` crate? Or at least into their own high level `p2p` module in the `tendermint` crate?
- [ ] What else might bring clarity to where/how certain types and functionality are used?

**Comment by tony-iqlusion** [comment]
Some quick notes:

- `crypto` and `config` are definitely great candidates for a `tendermint-crypto`/`tendermint-config` crates. `crypto` would be useful independently anywhere you want support for key formats and cryptography ops. I'll note we're presently using the `config` crate with Sagan (to parse various validator settings from the config, as Sagan runs as a sidecar), but I imagine it'll eventually be useful for a Rust full node as well.
- Moving the modules you suggested to the `tendermint-p2p` crate might make sense. Pretty much everything we've written so far (TMKMS, Sagan, Delphi) relies on the `net` types in some form, but TMKMS is the only thing using `p2p` at the moment.
